// birds-data.ts
// Pure data + types for the Bird Bingo page.

export type BirdInfo = {
  // Top-of-card meta
  scientificName?: string;
  order?: string;
  family?: string;
  groupName?: string; // e.g. "Rails", "Buntings"

  // Icon row
  habitat?: string; // "Lakes and ponds"
  food?: string; // "Plants"
  nesting?: string; // "Floating"
  behavior?: string; // "Surface dive"
  conservation?: string; // "Low concern"

  // Text blocks
  basicDescription?: string;
  songs?: string;
  calls?: string;
  otherSounds?: string;

  // Links
  sourceUrl?: string; // main Cornell species page
  lifeHistoryUrl?: string; // optional life history subpage
};

export type BirdSongVariant = {
  id: string;
  label: string;
  audio: string;
  note?: string;
};

export type Bird = {
  id: string;
  name: string;
  image?: string;
  imageMale?: string;
  imageFemale?: string;
  voice: string;
  call: string;
  info?: BirdInfo;
  variants?: BirdSongVariant[];
};

export const birds: Bird[] = [
  {
    id: "american-coot",
    name: "American Coot",
    imageMale: "/bird-bingo/birds/img/american-coot-male.png",
    imageFemale: "/bird-bingo/birds/img/american-coot-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/american-coot-voice.mp3",
    call: "/bird-bingo/birds/audio/american-coot-call.mp3",
    info: {
      scientificName: "Fulica americana",
      order: "Gruiformes",
      family: "Rallidae",
      groupName: "Rails",
      habitat: "Lakes and ponds",
      food: "Plants",
      nesting: "Floating",
      behavior: "Surface dive",
      conservation: "Low concern",
      basicDescription:
        "Stocky, dark waterbirds that cruise around open ponds and marshes with a stark white bill and forehead shield. They often forage alongside ducks, but a closer look at their slim head and long lobed toes reveals that coots are actually rails, more closely related to Sandhill Cranes and secretive marsh birds than to true ducks.",
      songs:
        "Gives series of short clucks, croaks, and grunts, often strung together into chattering, mechanical-sounding phrases.",
      calls:
        "Loud cackles, honks, and squawks used in contact, aggression, and alarm when squabbling on the water.",
      otherSounds:
        "Splashy, slapping footsteps as they run across the water during takeoff or fights, plus noisy wingbeats over the pond.",
      sourceUrl: "https://www.allaboutbirds.org/guide/American_Coot",
      lifeHistoryUrl:
        "https://www.allaboutbirds.org/guide/American_Coot/lifehistory",
    },
    variants: [
      {
        id: "american-coot-classic-song",
        label: "Classic song",
        audio: "/bird-bingo/birds/audio/american-coot-classic-song.mp3",
      },
      {
        id: "american-coot-pnw-dialect",
        label: "PNW dialect",
        audio: "/bird-bingo/birds/audio/american-coot-pnw-dialect.mp3",
      },
    ],
  },
  {
    id: "american-crow",
    name: "American Crow",
    imageMale: "/bird-bingo/birds/img/american-crow-male.png",
    imageFemale: "/bird-bingo/birds/img/american-crow-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/american-crow-voice.mp3",
    call: "/bird-bingo/birds/audio/american-crow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-goldfinch",
    name: "American Goldfinch",
    imageMale: "/bird-bingo/birds/img/american-goldfinch-male.png",
    imageFemale: "/bird-bingo/birds/img/american-goldfinch-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/american-goldfinch-voice.mp3",
    call: "/bird-bingo/birds/audio/american-goldfinch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-redstart",
    name: "American Redstart",
    imageMale: "/bird-bingo/birds/img/american-redstart-male.png",
    imageFemale: "/bird-bingo/birds/img/american-redstart-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/american-redstart-voice.mp3",
    call: "/bird-bingo/birds/audio/american-redstart-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-robin",
    name: "American Robin",
    imageMale: "/bird-bingo/birds/img/american-robin-male.png",
    imageFemale: "/bird-bingo/birds/img/american-robin-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/american-robin-voice.mp3",
    call: "/bird-bingo/birds/audio/american-robin-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "bald-eagle",
    name: "Bald Eagle",
    imageMale: "/bird-bingo/birds/img/bald-eagle-male.png",
    imageFemale: "/bird-bingo/birds/img/bald-eagle-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/bald-eagle-voice.mp3",
    call: "/bird-bingo/birds/audio/bald-eagle-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "baltimore-oriole",
    name: "Baltimore Oriole",
    imageMale: "/bird-bingo/birds/img/baltimore-oriole-male.png",
    imageFemale: "/bird-bingo/birds/img/baltimore-oriole-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/baltimore-oriole-voice.mp3",
    call: "/bird-bingo/birds/audio/baltimore-oriole-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "belted-kingfisher",
    name: "Belted Kingfisher",
    imageMale: "/bird-bingo/birds/img/belted-kingfisher-male.png",
    imageFemale: "/bird-bingo/birds/img/belted-kingfisher-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/belted-kingfisher-voice.mp3",
    call: "/bird-bingo/birds/audio/belted-kingfisher-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "black-capped-chickadee",
    name: "Black-capped Chickadee",
    imageMale: "/bird-bingo/birds/img/black-capped-chickadee-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/black-capped-chickadee-voice.mp3",
    call: "/bird-bingo/birds/audio/black-capped-chickadee-call.mp3",
    info: {},
    variants: [
      {
        id: "bcc-fee-bee",
        label: "Fee-bee song",
        audio: "/bird-bingo/birds/audio/black-capped-chickadee-fee-bee.mp3",
      },
      {
        id: "bcc-gargle",
        label: "Gargle call",
        audio: "/bird-bingo/birds/audio/black-capped-chickadee-gargle.mp3",
      },
      {
        id: "bcc-high-see",
        label: "High see alarm",
        audio: "/bird-bingo/birds/audio/black-capped-chickadee-high-see.mp3",
      },
    ],
  },
  {
    id: "black-phoebe",
    name: "Black Phoebe",
    imageMale: "/bird-bingo/birds/img/black-phoebe-male.png",
    imageFemale: "/bird-bingo/birds/img/black-phoebe-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/black-phoebe-voice.mp3",
    call: "/bird-bingo/birds/audio/black-phoebe-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "blue-jay",
    name: "Blue Jay",
    imageMale: "/bird-bingo/birds/img/blue-jay-male.png",
    imageFemale: "/bird-bingo/birds/img/blue-jay-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/blue-jay-voice.mp3",
    call: "/bird-bingo/birds/audio/blue-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "brown-pelican",
    name: "Brown Pelican",
    imageMale: "/bird-bingo/birds/img/brown-pelican-male.png",
    imageFemale: "/bird-bingo/birds/img/brown-pelican-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/brown-pelican-voice.mp3",
    call: "/bird-bingo/birds/audio/brown-pelican-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "bufflehead",
    name: "Bufflehead",
    imageMale: "/bird-bingo/birds/img/bufflehead-male.png",
    imageFemale: "/bird-bingo/birds/img/bufflehead-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/bufflehead-voice.mp3",
    call: "/bird-bingo/birds/audio/bufflehead-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "california-quail",
    name: "California Quail",
    imageMale: "/bird-bingo/birds/img/california-quail-male.png",
    imageFemale: "/bird-bingo/birds/img/california-quail-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/california-quail-voice.mp3",
    call: "/bird-bingo/birds/audio/california-quail-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "california-scrub-jay",
    name: "California Scrub-Jay",
    imageMale: "/bird-bingo/birds/img/california-scrub-jay-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/california-scrub-jay-voice.mp3",
    call: "/bird-bingo/birds/audio/california-scrub-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "canada-goose",
    name: "Canada Goose",
    imageMale: "/bird-bingo/birds/img/canada-goose-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/canada-goose-voice.mp3",
    call: "/bird-bingo/birds/audio/canada-goose-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "carolina-wren",
    name: "Carolina Wren",
    imageMale: "/bird-bingo/birds/img/carolina-wren-male.png",
    imageFemale: "/bird-bingo/birds/img/carolina-wren-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/carolina-wren-voice.mp3",
    call: "/bird-bingo/birds/audio/carolina-wren-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "cedar-waxwing",
    name: "Cedar Waxwing",
    imageMale: "/bird-bingo/birds/img/cedar-waxwing-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/cedar-waxwing-voice.mp3",
    call: "/bird-bingo/birds/audio/cedar-waxwing-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "common-loon",
    name: "Common Loon",
    imageMale: "/bird-bingo/birds/img/common-loon-male.png",
    imageFemale: "/bird-bingo/birds/img/common-loon-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/common-loon-voice.mp3",
    call: "/bird-bingo/birds/audio/common-loon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "dark-eyed-junco",
    name: "Dark-Eyed Junco",
    imageMale: "/bird-bingo/birds/img/dark-eyed-junco-male.png",
    imageFemale: "/bird-bingo/birds/img/dark-eyed-junco-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/dark-eyed-junco-voice.mp3",
    call: "/bird-bingo/birds/audio/dark-eyed-junco-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "double-crested-cormorant",
    name: "Double-crested Cormorant",
    imageMale: "/bird-bingo/birds/img/double-crested-cormorant-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/double-crested-cormorant-voice.mp3",
    call: "/bird-bingo/birds/audio/double-crested-cormorant-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "eastern-bluebird",
    name: "Eastern Bluebird",
    imageMale: "/bird-bingo/birds/img/eastern-bluebird-male.png",
    imageFemale: "/bird-bingo/birds/img/eastern-bluebird-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/eastern-bluebird-voice.mp3",
    call: "/bird-bingo/birds/audio/eastern-bluebird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "great-blue-heron",
    name: "Great Blue Heron",
    imageMale: "/bird-bingo/birds/img/great-blue-heron-male.png",
    imageFemale: "/bird-bingo/birds/img/great-blue-heron-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/great-blue-heron-voice.mp3",
    call: "/bird-bingo/birds/audio/great-blue-heron-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "great-horned-owl",
    name: "Great Horned Owl",
    imageMale: "/bird-bingo/birds/img/great-horned-owl-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/great-horned-owl-voice.mp3",
    call: "/bird-bingo/birds/audio/great-horned-owl-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "house-finch",
    name: "House Finch",
    imageMale: "/bird-bingo/birds/img/house-finch-male.png",
    imageFemale: "/bird-bingo/birds/img/house-finch-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/house-finch-voice.mp3",
    call: "/bird-bingo/birds/audio/house-finch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "house-sparrow",
    name: "House Sparrow",
    imageMale: "/bird-bingo/birds/img/house-sparrow-male.png",
    imageFemale: "/bird-bingo/birds/img/house-sparrow-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/house-sparrow-voice.mp3",
    call: "/bird-bingo/birds/audio/house-sparrow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "indigo-bunting",
    name: "Indigo Bunting",
    imageMale: "/bird-bingo/birds/img/indigo-bunting-male.png",
    imageFemale: "/bird-bingo/birds/img/indigo-bunting-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/indigo-bunting-voice.mp3",
    call: "/bird-bingo/birds/audio/indigo-bunting-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "killdeer",
    name: "Killdeer",
    imageMale: "/bird-bingo/birds/img/killdeer-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/killdeer-voice.mp3",
    call: "/bird-bingo/birds/audio/killdeer-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "laughing-gull",
    name: "Laughing Gull",
    imageMale: "/bird-bingo/birds/img/laughing-gull-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/laughing-gull-voice.mp3",
    call: "/bird-bingo/birds/audio/laughing-gull-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mallard",
    name: "Mallard",
    imageMale: "/bird-bingo/birds/img/mallard-male.png",
    imageFemale: "/bird-bingo/birds/img/mallard-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/mallard-voice.mp3",
    call: "/bird-bingo/birds/audio/mallard-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mourning-dove",
    name: "Mourning Dove",
    imageMale: "/bird-bingo/birds/img/mourning-dove-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/mourning-dove-voice.mp3",
    call: "/bird-bingo/birds/audio/mourning-dove-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mute-swan",
    name: "Mute Swan",
    imageMale: "/bird-bingo/birds/img/mute-swan-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/mute-swan-voice.mp3",
    call: "/bird-bingo/birds/audio/mute-swan-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-cardinal",
    name: "Northern Cardinal",
    imageMale: "/bird-bingo/birds/img/northern-cardinal-male.png",
    imageFemale: "/bird-bingo/birds/img/northern-cardinal-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/northern-cardinal-voice.mp3",
    call: "/bird-bingo/birds/audio/northern-cardinal-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-flicker",
    name: "Northern Flicker",
    imageMale: "/bird-bingo/birds/img/northern-flicker-male.png",
    imageFemale: "/bird-bingo/birds/img/northern-flicker-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/northern-flicker-voice.mp3",
    call: "/bird-bingo/birds/audio/northern-flicker-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-mockingbird",
    name: "Northern Mockingbird",
    imageMale: "/bird-bingo/birds/img/northern-mockingbird-male.png",
    imageFemale: "/bird-bingo/birds/img/northern-mockingbird-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/northern-mockingbird-voice.mp3",
    call: "/bird-bingo/birds/audio/northern-mockingbird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "pileated-woodpecker",
    name: "Pileated Woodpecker",
    imageMale: "/bird-bingo/birds/img/pileated-woodpecker-male.png",
    imageFemale: "/bird-bingo/birds/img/pileated-woodpecker-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/pileated-woodpecker-voice.mp3",
    call: "/bird-bingo/birds/audio/pileated-woodpecker-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "red-tailed-hawk",
    name: "Red-Tailed Hawk",
    imageMale: "/bird-bingo/birds/img/red-tailed-hawk-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/red-tailed-hawk-voice.mp3",
    call: "/bird-bingo/birds/audio/red-tailed-hawk-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "ring-billed-gull",
    name: "Ring-Billed Gull",
    imageMale: "/bird-bingo/birds/img/ring-billed-gull-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/ring-billed-gull-voice.mp3",
    call: "/bird-bingo/birds/audio/ring-billed-gull-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "rock-pigeon",
    name: "Rock Pigeon",
    imageMale: "/bird-bingo/birds/img/rock-pigeon-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/rock-pigeon-voice.mp3",
    call: "/bird-bingo/birds/audio/rock-pigeon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "rose-breasted-grosbeak",
    name: "Rose-breasted Grosbeak",
    imageMale: "/bird-bingo/birds/img/rose-breasted-grosbeak-male.png",
    imageFemale: "/bird-bingo/birds/img/rose-breasted-grosbeak-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/rose-breasted-grosbeak-voice.mp3",
    call: "/bird-bingo/birds/audio/rose-breasted-grosbeak-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "ruby-throated-hummingbird",
    name: "Ruby Throated Hummingbird",
    imageMale: "/bird-bingo/birds/img/ruby-throated-hummingbird-male.png",
    imageFemale: "/bird-bingo/birds/img/ruby-throated-hummingbird-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/ruby-throated-hummingbird-voice.mp3",
    call: "/bird-bingo/birds/audio/ruby-throated-hummingbird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "sandhill-crane",
    name: "Sandhill Crane",
    imageMale: "/bird-bingo/birds/img/sandhill-crane-male.png",
    imageFemale: "/bird-bingo/birds/img/sandhill-crane-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/sandhill-crane-voice.mp3",
    call: "/bird-bingo/birds/audio/sandhill-crane-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "scarlet-tanager",
    name: "Scarlet Tanager",
    imageMale: "/bird-bingo/birds/img/scarlet-tanager-male.png",
    imageFemale: "/bird-bingo/birds/img/scarlet-tanager-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/scarlet-tanager-voice.mp3",
    call: "/bird-bingo/birds/audio/scarlet-tanager-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "spotted-towhee",
    name: "Spotted Towhee",
    imageMale: "/bird-bingo/birds/img/spotted-towhee-male.png",
    imageFemale: "/bird-bingo/birds/img/spotted-towhee-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/spotted-towhee-voice.mp3",
    call: "/bird-bingo/birds/audio/spotted-towhee-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "stellers-jay",
    name: "Steller's Jay",
    imageMale: "/bird-bingo/birds/img/stellers-jay-male.png",
    imageFemale: "/bird-bingo/birds/img/stellers-jay-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/stellers-jay-voice.mp3",
    call: "/bird-bingo/birds/audio/stellers-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "swainsons-thrush",
    name: "Swainson's Thrush",
    imageMale: "/bird-bingo/birds/img/swainsons-thrush-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/swainsons-thrush-voice.mp3",
    call: "/bird-bingo/birds/audio/swainsons-thrush-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "tree-swallow",
    name: "Tree Swallow",
    imageMale: "/bird-bingo/birds/img/tree-swallow-male.png",
    imageFemale: "/bird-bingo/birds/img/tree-swallow-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/tree-swallow-voice.mp3",
    call: "/bird-bingo/birds/audio/tree-swallow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "tufted-titmouse",
    name: "Tufted Titmouse",
    imageMale: "/bird-bingo/birds/img/tufted-titmouse-male.png",
    imageFemale: "/bird-bingo/birds/img/tufted-titmouse-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/tufted-titmouse-voice.mp3",
    call: "/bird-bingo/birds/audio/tufted-titmouse-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "western-meadowlark",
    name: "Western Meadowlark",
    imageMale: "/bird-bingo/birds/img/western-meadowlark-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/western-meadowlark-voice.mp3",
    call: "/bird-bingo/birds/audio/western-meadowlark-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "western-tanager",
    name: "Western Tanager",
    imageMale: "/bird-bingo/birds/img/western-tanager-male.png",
    imageFemale: "/bird-bingo/birds/img/western-tanager-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/western-tanager-voice.mp3",
    call: "/bird-bingo/birds/audio/western-tanager-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "white-breasted-nuthatch",
    name: "White-Breasted Nuthatch",
    imageMale: "/bird-bingo/birds/img/white-breasted-nuthatch-male.png",
    imageFemale: "/bird-bingo/birds/img/white-breasted-nuthatch-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/white-breasted-nuthatch-voice.mp3",
    call: "/bird-bingo/birds/audio/white-breasted-nuthatch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "white-throated-sparrow",
    name: "White-Throated Sparrow",
    imageMale: "/bird-bingo/birds/img/white-throated-sparrow-male.png",
    imageFemale: "/bird-bingo/birds/img/white-throated-sparrow-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/white-throated-sparrow-voice.mp3",
    call: "/bird-bingo/birds/audio/white-throated-sparrow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "wood-duck",
    name: "Wood Duck",
    imageMale: "/bird-bingo/birds/img/wood-duck-male.png",
    imageFemale: "/bird-bingo/birds/img/wood-duck-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/wood-duck-voice.mp3",
    call: "/bird-bingo/birds/audio/wood-duck-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "yellow-rumped-warbler",
    name: "Yellow-Rumped Warbler",
    imageMale: "/bird-bingo/birds/img/yellow-rumped-warbler-male.png",
    imageFemale: "/bird-bingo/birds/img/yellow-rumped-warbler-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/yellow-rumped-warbler-voice.mp3",
    call: "/bird-bingo/birds/audio/yellow-rumped-warbler-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  // ── New species ─────────────────────────────────────────────
  {
    id: "atlantic-puffin",
    name: "Atlantic Puffin",
    imageMale: "/bird-bingo/birds/img/atlantic-puffin-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/atlantic-puffin-voice.mp3",
    call: "/bird-bingo/birds/audio/atlantic-puffin-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "barn-owl",
    name: "Barn Owl",
    imageMale: "/bird-bingo/birds/img/barn-owl-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/barn-owl-voice.mp3",
    call: "/bird-bingo/birds/audio/barn-owl-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "blue-footed-booby",
    name: "Blue-footed Booby",
    imageMale: "/bird-bingo/birds/img/blue-footed-booby-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/blue-footed-booby-voice.mp3",
    call: "/bird-bingo/birds/audio/blue-footed-booby-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "cassowary",
    name: "Southern Cassowary",
    imageMale: "/bird-bingo/birds/img/southern-cassowary-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/southern-cassowary-voice.mp3",
    call: "/bird-bingo/birds/audio/southern-cassowary-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "emperor-penguin",
    name: "Emperor Penguin",
    imageMale: "/bird-bingo/birds/img/emperor-penguin-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/emperor-penguin-voice.mp3",
    call: "/bird-bingo/birds/audio/emperor-penguin-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "flamingo",
    name: "American Flamingo",
    imageMale: "/bird-bingo/birds/img/american-flamingo-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/american-flamingo-voice.mp3",
    call: "/bird-bingo/birds/audio/american-flamingo-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "great-cormorant",
    name: "Great Cormorant",
    imageMale: "/bird-bingo/birds/img/great-cormorant-male.png",
    imageFemale: "/bird-bingo/birds/img/great-cormorant-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/great-cormorant-voice.mp3",
    call: "/bird-bingo/birds/audio/great-cormorant-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "harpy-eagle",
    name: "Harpy Eagle",
    imageMale: "/bird-bingo/birds/img/harpy-eagle-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/harpy-eagle-voice.mp3",
    call: "/bird-bingo/birds/audio/harpy-eagle-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "indian-peafowl",
    name: "Indian Peafowl",
    imageMale: "/bird-bingo/birds/img/indian-peafowl-male.png",
    imageFemale: "/bird-bingo/birds/img/indian-peafowl-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/indian-peafowl-voice.mp3",
    call: "/bird-bingo/birds/audio/indian-peafowl-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "keel-billed-toucan",
    name: "Keel-billed Toucan",
    imageMale: "/bird-bingo/birds/img/keel-billed-toucan-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/keel-billed-toucan-voice.mp3",
    call: "/bird-bingo/birds/audio/keel-billed-toucan-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "kookaburra",
    name: "Laughing Kookaburra",
    imageMale: "/bird-bingo/birds/img/kookaburra-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/kookaburra-voice.mp3",
    call: "/bird-bingo/birds/audio/kookaburra-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "lyrebird",
    name: "Superb Lyrebird",
    imageMale: "/bird-bingo/birds/img/superb-lyrebird-male.png",
    imageFemale: "/bird-bingo/birds/img/superb-lyrebird-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/lyrebird-voice.mp3",
    call: "/bird-bingo/birds/audio/lyrebird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "ostrich",
    name: "Common Ostrich",
    imageMale: "/bird-bingo/birds/img/common-ostrich-male.png",
    imageFemale: "/bird-bingo/birds/img/common-ostrich-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/common-ostrich-voice.mp3",
    call: "/bird-bingo/birds/audio/common-ostrich-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "red-winged-blackbird",
    name: "Red-winged Blackbird",
    imageMale: "/bird-bingo/birds/img/red-winged-blackbird-male.png",
    imageFemale: "/bird-bingo/birds/img/red-winged-blackbird-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/red-winged-blackbird-voice.mp3",
    call: "/bird-bingo/birds/audio/red-winged-blackbird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "secretary-bird",
    name: "Secretary Bird",
    imageMale: "/bird-bingo/birds/img/secretary-bird-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/secretary-bird-voice.mp3",
    call: "/bird-bingo/birds/audio/secretary-bird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "snowy-owl",
    name: "Snowy Owl",
    imageMale: "/bird-bingo/birds/img/snowy-owl-male.png",
    imageFemale: "/bird-bingo/birds/img/snowy-owl-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/snowy-owl-voice.mp3",
    call: "/bird-bingo/birds/audio/snowy-owl-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "african-fish-eagle",
    name: "African Fish Eagle",
    imageMale: "/bird-bingo/birds/img/african-fish-eagle-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/african-fish-eagle-voice.mp3",
    call: "/bird-bingo/birds/audio/african-fish-eagle-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "blyths-kingfisher",
    name: "Blyth's Kingfisher",
    imageMale: "/bird-bingo/birds/img/blyths-kingfisher-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/blyths-kingfisher-voice.mp3",
    call: "/bird-bingo/birds/audio/blyths-kingfisher-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "budgie",
    name: "Budgerigar",
    imageMale: "/bird-bingo/birds/img/budgie-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/budgie-voice.mp3",
    call: "/bird-bingo/birds/audio/budgie-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "chicken",
    name: "Chicken",
    imageMale: "/bird-bingo/birds/img/chicken-male.png",
    imageFemale: "/bird-bingo/birds/img/chicken-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/chicken-voice.mp3",
    call: "/bird-bingo/birds/audio/chicken-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "crimson-rosella",
    name: "Crimson Rosella",
    imageMale: "/bird-bingo/birds/img/crimson-rosella-male.png",
    imageFemale: "/bird-bingo/birds/img/crimson-rosella-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/crimson-rosella-voice.mp3",
    call: "/bird-bingo/birds/audio/crimson-rosella-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "cuckoo",
    name: "Common Cuckoo",
    imageMale: "/bird-bingo/birds/img/cuckoo-male.png",
    imageFemale: "/bird-bingo/birds/img/cuckoo-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/cuckoo-voice.mp3",
    call: "/bird-bingo/birds/audio/cuckoo-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "emu",
    name: "Emu",
    imageMale: "/bird-bingo/birds/img/emu-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/emu-voice.mp3",
    call: "/bird-bingo/birds/audio/emu-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "eurasian-golden-oriole",
    name: "Eurasian Golden Oriole",
    imageMale: "/bird-bingo/birds/img/eurasian-golden-oriole-male.png",
    imageFemale: "/bird-bingo/birds/img/eurasian-golden-oriole-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/eurasian-golden-oriole-voice.mp3",
    call: "/bird-bingo/birds/audio/eurasian-golden-oriole-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "eurasian-hoopoe",
    name: "Eurasian Hoopoe",
    imageMale: "/bird-bingo/birds/img/eurasian-hoopoe-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/eurasian-hoopoe-voice.mp3",
    call: "/bird-bingo/birds/audio/eurasian-hoopoe-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "eurasian-skylark",
    name: "Eurasian Skylark",
    imageMale: "/bird-bingo/birds/img/eurasian-skylark-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/eurasian-skylark-voice.mp3",
    call: "/bird-bingo/birds/audio/eurasian-skylark-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "european-nightingale",
    name: "Common Nightingale",
    imageMale: "/bird-bingo/birds/img/european-nightingale-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/european-nightingale-voice.mp3",
    call: "/bird-bingo/birds/audio/european-nightingale-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "greater-racket-tailed-drongo",
    name: "Greater Racket-tailed Drongo",
    imageMale: "/bird-bingo/birds/img/greater-racket-tailed-drongo-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/greater-racket-tailed-drongo-voice.mp3",
    call: "/bird-bingo/birds/audio/greater-racket-tailed-drongo-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "indian-koel",
    name: "Asian Koel",
    imageMale: "/bird-bingo/birds/img/indian-koel-male.png",
    imageFemale: "/bird-bingo/birds/img/indian-koel-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/indian-koel-voice.mp3",
    call: "/bird-bingo/birds/audio/indian-koel-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "japanese-tit",
    name: "Japanese Tit",
    imageMale: "/bird-bingo/birds/img/japanese-tit-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/japanese-tit-voice.mp3",
    call: "/bird-bingo/birds/audio/japanese-tit-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "kiwi",
    name: "North Island Brown Kiwi",
    imageMale: "/bird-bingo/birds/img/kiwi-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/kiwi-voice.mp3",
    call: "/bird-bingo/birds/audio/kiwi-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "macaw",
    name: "Scarlet Macaw",
    imageMale: "/bird-bingo/birds/img/macaw-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/macaw-voice.mp3",
    call: "/bird-bingo/birds/audio/macaw-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "white-bellied-sea-eagle",
    name: "White-bellied Sea Eagle",
    imageMale: "/bird-bingo/birds/img/white-bellied-sea-eagle-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/white-bellied-sea-eagle-voice.mp3",
    call: "/bird-bingo/birds/audio/white-bellied-sea-eagle-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "nicobar-pigeon",
    name: "Nicobar Pigeon",
    imageMale: "/bird-bingo/birds/img/nicobar-pigeon-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/nicobar-pigeon-voice.mp3",
    call: "/bird-bingo/birds/audio/nicobar-pigeon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "rainbow-lorikeet",
    name: "Rainbow Lorikeet",
    imageMale: "/bird-bingo/birds/img/rainbow-lorikeet-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/rainbow-lorikeet-voice.mp3",
    call: "/bird-bingo/birds/audio/rainbow-lorikeet-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "red-bearded-bee-eater",
    name: "Red-bearded Bee-eater",
    imageMale: "/bird-bingo/birds/img/red-bearded-bee-eater-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/red-bearded-bee-eater-voice.mp3",
    call: "/bird-bingo/birds/audio/red-bearded-bee-eater-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "resplendent-quetzal",
    name: "Resplendent Quetzal",
    imageMale: "/bird-bingo/birds/img/resplendent-quetzal-male.png",
    imageFemale: "/bird-bingo/birds/img/resplendent-quetzal-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/resplendent-quetzal-voice.mp3",
    call: "/bird-bingo/birds/audio/resplendent-quetzal-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "splendid-fairywren",
    name: "Splendid Fairywren",
    imageMale: "/bird-bingo/birds/img/splendid-fairywren-male.png",
    imageFemale: "/bird-bingo/birds/img/splendid-fairywren-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/splendid-fairywren-voice.mp3",
    call: "/bird-bingo/birds/audio/splendid-fairywren-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "victoria-crowned-pigeon",
    name: "Victoria Crowned Pigeon",
    imageMale: "/bird-bingo/birds/img/victoria-crowned-pigeon-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/victoria-crowned-pigeon-voice.mp3",
    call: "/bird-bingo/birds/audio/victoria-crowned-pigeon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "golden-pheasant",
    name: "Golden Pheasant",
    imageMale: "/bird-bingo/birds/img/golden-pheasant-male.png",
    imageFemale: "/bird-bingo/birds/img/golden-pheasant-female.png",
    image: "",
    voice: "/bird-bingo/birds/audio/golden-pheasant-voice.mp3",
    call: "/bird-bingo/birds/audio/golden-pheasant-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "scarlet-macaw",
    name: "Scarlet Macaw",
    imageMale: "/bird-bingo/birds/img/scarlet-macaw-male.png",
    imageFemale: "",
    image: "",
    voice: "/bird-bingo/birds/audio/scarlet-macaw-voice.mp3",
    call: "/bird-bingo/birds/audio/scarlet-macaw-call.mp3",
    info: { songs: "" },
    variants: [],
  },
];
